"""Monodromy group <rho, tau>: the group acting on the dart set.

The full monodromy group of a graph embedding is the subgroup of S_{2E}
generated by rho and tau. For Phase 4 v2 we do not enumerate the whole
group (it can be exponentially large); instead we expose the data that
downstream consumers actually need:

  - the order of rho, tau, and rho*tau
  - per-dart orbit lengths under rho (vertex valence cycles)
  - per-dart orbit lengths under tau (always 2; trivial)
  - per-dart orbit lengths under rho*tau (face cycles - "face" = closed walk
    alternating around a face of the embedding)
  - a "monodromy class" tag per dart: a tuple (rho_orbit_length,
    rho_tau_orbit_length) acting as a coarse signature

These signatures are what the singularity detector consumes as its
"stabilizer_jump" / "monodromy_class_changed" signal in Phase 4 v2.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from nga.arch.dart_permutations import (
    DartSet,
    compose,
    permutation_order,
)

__all__ = ["MonodromyData", "compute_monodromy", "cycle_lengths", "encode_monodromy_class"]


@dataclass
class MonodromyData:
    """Full monodromy data for a dart set.

    Attributes
    ----------
    rho:
        Shape (n_darts,). The rho permutation (rotation around vertices).
    tau:
        Shape (n_darts,). The tau permutation (edge flip; an involution).
    rho_tau:
        Shape (n_darts,). The composition rho composed with tau (face-tracing).
    rho_order:
        Order of rho in S_{n_darts}: smallest k > 0 with rho^k = id.
    tau_order:
        Order of tau; always 2 when tau is a proper involution.
    rho_tau_order:
        Order of rho*tau; gives the LCM of face lengths.
    rho_orbit_length:
        Shape (n_darts,). For each dart d, the length of the cycle of d under rho.
        This equals the degree (valence) of the base vertex of d.
    rho_tau_orbit_length:
        Shape (n_darts,). For each dart d, the length of the cycle of d under
        rho*tau. This is the length of the face containing dart d in the
        embedded graph.
    monodromy_class:
        Shape (n_darts,) of int. An opaque integer label per dart encoding
        (rho_orbit_length, rho_tau_orbit_length). Darts sharing the same label
        have the same coarse monodromy type. Treat as a categorical variable.
    """

    rho: np.ndarray                    # shape (n_darts,)
    tau: np.ndarray                    # shape (n_darts,)
    rho_tau: np.ndarray                # rho composed with tau: face-tracing
    rho_order: int
    tau_order: int                     # always 2 (tau is an involution)
    rho_tau_order: int
    rho_orbit_length: np.ndarray       # shape (n_darts,) - cycle length of dart under rho
    rho_tau_orbit_length: np.ndarray   # shape (n_darts,) - cycle length under rho*tau (face length)
    monodromy_class: np.ndarray        # shape (n_darts,) of int - tuple-encoded class


def cycle_lengths(perm: np.ndarray) -> np.ndarray:
    """For each index i, the length of the cycle containing i in perm.

    Traces cycles directly without full cycle enumeration overhead.

    Parameters
    ----------
    perm:
        Shape (n,) of int. A valid permutation on 0..n-1.

    Returns
    -------
    np.ndarray
        Shape (n,) of int. Entry i gives the length of the cycle containing i.
    """
    n = len(perm)
    lengths = np.zeros(n, dtype=int)
    visited = np.zeros(n, dtype=bool)

    for start in range(n):
        if visited[start]:
            continue
        # Trace the cycle from this start point.
        cycle: list[int] = []
        cur = start
        while not visited[cur]:
            visited[cur] = True
            cycle.append(cur)
            cur = int(perm[cur])
        # Assign the cycle length to every element in the cycle.
        clen = len(cycle)
        for idx in cycle:
            lengths[idx] = clen

    return lengths


def encode_monodromy_class(rho_len: int, rho_tau_len: int) -> int:
    """Pack (rho_len, rho_tau_len) into a single int for use as a label.

    Use 16-bit packing: (rho_len << 16) | rho_tau_len. Both fit in 16 bits
    for any sensible graph size. Documented as opaque; clients should treat
    it as a categorical label.

    Parameters
    ----------
    rho_len:
        Cycle length of a dart under rho (vertex valence). Must fit in 16 bits.
    rho_tau_len:
        Cycle length of a dart under rho*tau (face length). Must fit in 16 bits.

    Returns
    -------
    int
        Opaque integer label encoding (rho_len, rho_tau_len).
    """
    return (int(rho_len) << 16) | int(rho_tau_len)


def compute_monodromy(rho: np.ndarray, tau: np.ndarray) -> MonodromyData:
    """Compute the full monodromy data from rho and tau.

    Computes rho*tau (face-tracing permutation), cycle lengths for rho and
    rho*tau, the permutation orders, and the per-dart monodromy class labels.

    Parameters
    ----------
    rho:
        Shape (n_darts,) of int. The rho permutation (vertex rotation).
    tau:
        Shape (n_darts,) of int. The tau permutation (edge flip).

    Returns
    -------
    MonodromyData
        Fully populated monodromy data structure.
    """
    rho_tau = compose(rho, tau)

    rho_order = permutation_order(rho)
    tau_order = permutation_order(tau)
    rho_tau_order = permutation_order(rho_tau)

    rho_orbit_len = cycle_lengths(rho)
    rho_tau_orbit_len = cycle_lengths(rho_tau)

    # Encode monodromy class per dart.
    n = len(rho)
    monodromy_class = np.empty(n, dtype=int)
    for d in range(n):
        monodromy_class[d] = encode_monodromy_class(
            int(rho_orbit_len[d]),
            int(rho_tau_orbit_len[d]),
        )

    return MonodromyData(
        rho=rho,
        tau=tau,
        rho_tau=rho_tau,
        rho_order=rho_order,
        tau_order=tau_order,
        rho_tau_order=rho_tau_order,
        rho_orbit_length=rho_orbit_len,
        rho_tau_orbit_length=rho_tau_orbit_len,
        monodromy_class=monodromy_class,
    )
